[2025-04-28T06:45:24.466+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Airflow_ETL_DAG.insert_locations scheduled__2025-03-10T00:00:00+00:00 [queued]>
[2025-04-28T06:45:24.476+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Airflow_ETL_DAG.insert_locations scheduled__2025-03-10T00:00:00+00:00 [queued]>
[2025-04-28T06:45:24.476+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-04-28T06:45:24.494+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): insert_locations> on 2025-03-10 00:00:00+00:00
[2025-04-28T06:45:24.503+0000] {standard_task_runner.py:57} INFO - Started process 363 to run task
[2025-04-28T06:45:24.509+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'Airflow_ETL_DAG', 'insert_locations', 'scheduled__2025-03-10T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/airflow_etl.py', '--cfg-path', '/tmp/tmpo5jyuk7d']
[2025-04-28T06:45:24.512+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask insert_locations
[2025-04-28T06:45:24.613+0000] {task_command.py:416} INFO - Running <TaskInstance: Airflow_ETL_DAG.insert_locations scheduled__2025-03-10T00:00:00+00:00 [running]> on host 77b690a9fde8
[2025-04-28T06:45:24.767+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Airflow_ETL_DAG' AIRFLOW_CTX_TASK_ID='insert_locations' AIRFLOW_CTX_EXECUTION_DATE='2025-03-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-10T00:00:00+00:00'
[2025-04-28T06:45:25.810+0000] {logging_mixin.py:151} INFO - Insertion des locations terminée.
[2025-04-28T06:45:25.814+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-04-28T06:45:25.835+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=Airflow_ETL_DAG, task_id=insert_locations, execution_date=20250310T000000, start_date=20250428T064524, end_date=20250428T064525
[2025-04-28T06:45:25.933+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-04-28T06:45:25.982+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-03T07:22:07.995+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations permission to 509
[2025-05-03T07:22:07.996+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations'
[2025-05-03T07:22:08.036+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations permission to 509
[2025-05-03T07:22:08.036+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations'
[2025-05-03T07:22:08.080+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Airflow_ETL_DAG.insert_locations scheduled__2025-03-10T00:00:00+00:00 [queued]>
[2025-05-03T07:22:08.090+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Airflow_ETL_DAG.insert_locations scheduled__2025-03-10T00:00:00+00:00 [queued]>
[2025-05-03T07:22:08.091+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-05-03T07:22:08.103+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): insert_locations> on 2025-03-10 00:00:00+00:00
[2025-05-03T07:22:08.110+0000] {standard_task_runner.py:57} INFO - Started process 250 to run task
[2025-05-03T07:22:08.113+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'Airflow_ETL_DAG', 'insert_locations', 'scheduled__2025-03-10T00:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/airflow_etl.py', '--cfg-path', '/tmp/tmpooi0r1bk']
[2025-05-03T07:22:08.116+0000] {standard_task_runner.py:85} INFO - Job 2: Subtask insert_locations
[2025-05-03T07:22:08.174+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations permission to 509
[2025-05-03T07:22:08.175+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations'
[2025-05-03T07:22:08.176+0000] {task_command.py:416} INFO - Running <TaskInstance: Airflow_ETL_DAG.insert_locations scheduled__2025-03-10T00:00:00+00:00 [running]> on host f2b491f5d506
[2025-05-03T07:22:08.259+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Airflow_ETL_DAG' AIRFLOW_CTX_TASK_ID='insert_locations' AIRFLOW_CTX_EXECUTION_DATE='2025-03-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-10T00:00:00+00:00'
[2025-05-03T07:22:08.948+0000] {logging_mixin.py:151} INFO - Insertion des locations terminée.
[2025-05-03T07:22:08.951+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-05-03T07:22:08.963+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=Airflow_ETL_DAG, task_id=insert_locations, execution_date=20250310T000000, start_date=20250503T072208, end_date=20250503T072208
[2025-05-03T07:22:09.009+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-05-03T07:22:09.034+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-05T13:47:38.242+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations permission to 509
[2025-05-05T13:47:38.243+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations'
[2025-05-05T13:47:38.302+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations permission to 509
[2025-05-05T13:47:38.303+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations'
[2025-05-05T13:47:38.575+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Airflow_ETL_DAG.insert_locations scheduled__2025-03-10T00:00:00+00:00 [queued]>
[2025-05-05T13:47:38.585+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Airflow_ETL_DAG.insert_locations scheduled__2025-03-10T00:00:00+00:00 [queued]>
[2025-05-05T13:47:38.586+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-05-05T13:47:38.601+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): insert_locations> on 2025-03-10 00:00:00+00:00
[2025-05-05T13:47:38.611+0000] {standard_task_runner.py:57} INFO - Started process 206 to run task
[2025-05-05T13:47:38.614+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'Airflow_ETL_DAG', 'insert_locations', 'scheduled__2025-03-10T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/airflow_etl.py', '--cfg-path', '/tmp/tmp43b2vw8a']
[2025-05-05T13:47:38.617+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask insert_locations
[2025-05-05T13:47:38.682+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations permission to 509
[2025-05-05T13:47:38.683+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations'
[2025-05-05T13:47:38.685+0000] {task_command.py:416} INFO - Running <TaskInstance: Airflow_ETL_DAG.insert_locations scheduled__2025-03-10T00:00:00+00:00 [running]> on host 1cb5a07b27d6
[2025-05-05T13:47:38.781+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Airflow_ETL_DAG' AIRFLOW_CTX_TASK_ID='insert_locations' AIRFLOW_CTX_EXECUTION_DATE='2025-03-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-10T00:00:00+00:00'
[2025-05-05T13:47:39.502+0000] {logging_mixin.py:151} INFO - Insertion des locations terminée.
[2025-05-05T13:47:39.504+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-05-05T13:47:39.517+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=Airflow_ETL_DAG, task_id=insert_locations, execution_date=20250310T000000, start_date=20250505T134738, end_date=20250505T134739
[2025-05-05T13:47:39.593+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-05-05T13:47:39.623+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-10T17:03:02.198+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations permission to 509
[2025-05-10T17:03:02.199+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations'
[2025-05-10T17:03:02.264+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations permission to 509
[2025-05-10T17:03:02.264+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations'
[2025-05-10T17:03:02.387+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Airflow_ETL_DAG.insert_locations scheduled__2025-03-10T00:00:00+00:00 [queued]>
[2025-05-10T17:03:02.397+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Airflow_ETL_DAG.insert_locations scheduled__2025-03-10T00:00:00+00:00 [queued]>
[2025-05-10T17:03:02.398+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-05-10T17:03:02.453+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): insert_locations> on 2025-03-10 00:00:00+00:00
[2025-05-10T17:03:02.464+0000] {standard_task_runner.py:57} INFO - Started process 519 to run task
[2025-05-10T17:03:02.467+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'Airflow_ETL_DAG', 'insert_locations', 'scheduled__2025-03-10T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/airflow_etl.py', '--cfg-path', '/tmp/tmpgu33c1px']
[2025-05-10T17:03:02.471+0000] {standard_task_runner.py:85} INFO - Job 4: Subtask insert_locations
[2025-05-10T17:03:02.541+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations permission to 509
[2025-05-10T17:03:02.542+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations'
[2025-05-10T17:03:02.544+0000] {task_command.py:416} INFO - Running <TaskInstance: Airflow_ETL_DAG.insert_locations scheduled__2025-03-10T00:00:00+00:00 [running]> on host 45059e99c3e8
[2025-05-10T17:03:02.667+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Airflow_ETL_DAG' AIRFLOW_CTX_TASK_ID='insert_locations' AIRFLOW_CTX_EXECUTION_DATE='2025-03-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-10T00:00:00+00:00'
[2025-05-10T17:03:03.497+0000] {logging_mixin.py:151} INFO - Insertion des locations terminée.
[2025-05-10T17:03:03.499+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-05-10T17:03:03.514+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=Airflow_ETL_DAG, task_id=insert_locations, execution_date=20250310T000000, start_date=20250510T170302, end_date=20250510T170303
[2025-05-10T17:03:03.568+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-05-10T17:03:03.603+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-11T16:05:57.810+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations permission to 509
[2025-05-11T16:05:57.811+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations'
[2025-05-11T16:05:57.879+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations permission to 509
[2025-05-11T16:05:57.879+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations'
[2025-05-11T16:05:57.941+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Airflow_ETL_DAG.insert_locations scheduled__2025-03-10T00:00:00+00:00 [queued]>
[2025-05-11T16:05:57.955+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Airflow_ETL_DAG.insert_locations scheduled__2025-03-10T00:00:00+00:00 [queued]>
[2025-05-11T16:05:57.956+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-05-11T16:05:57.974+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): insert_locations> on 2025-03-10 00:00:00+00:00
[2025-05-11T16:05:57.989+0000] {standard_task_runner.py:57} INFO - Started process 261 to run task
[2025-05-11T16:05:57.993+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'Airflow_ETL_DAG', 'insert_locations', 'scheduled__2025-03-10T00:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/airflow_etl.py', '--cfg-path', '/tmp/tmp7tw41qj7']
[2025-05-11T16:05:57.997+0000] {standard_task_runner.py:85} INFO - Job 2: Subtask insert_locations
[2025-05-11T16:05:58.195+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations permission to 509
[2025-05-11T16:05:58.196+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations'
[2025-05-11T16:05:58.199+0000] {task_command.py:416} INFO - Running <TaskInstance: Airflow_ETL_DAG.insert_locations scheduled__2025-03-10T00:00:00+00:00 [running]> on host 9a7df5060863
[2025-05-11T16:05:58.400+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Airflow_ETL_DAG' AIRFLOW_CTX_TASK_ID='insert_locations' AIRFLOW_CTX_EXECUTION_DATE='2025-03-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-10T00:00:00+00:00'
[2025-05-11T16:05:59.675+0000] {logging_mixin.py:151} INFO - Insertion des locations terminée.
[2025-05-11T16:05:59.678+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-05-11T16:05:59.696+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=Airflow_ETL_DAG, task_id=insert_locations, execution_date=20250310T000000, start_date=20250511T160557, end_date=20250511T160559
[2025-05-11T16:05:59.774+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-05-11T16:05:59.814+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-12T09:21:24.512+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations permission to 509
[2025-05-12T09:21:24.513+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations'
[2025-05-12T09:21:24.580+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations permission to 509
[2025-05-12T09:21:24.580+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations'
[2025-05-12T09:21:24.797+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Airflow_ETL_DAG.insert_locations scheduled__2025-03-10T00:00:00+00:00 [queued]>
[2025-05-12T09:21:24.804+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Airflow_ETL_DAG.insert_locations scheduled__2025-03-10T00:00:00+00:00 [queued]>
[2025-05-12T09:21:24.805+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-05-12T09:21:24.815+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): insert_locations> on 2025-03-10 00:00:00+00:00
[2025-05-12T09:21:24.821+0000] {standard_task_runner.py:57} INFO - Started process 233 to run task
[2025-05-12T09:21:24.826+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'Airflow_ETL_DAG', 'insert_locations', 'scheduled__2025-03-10T00:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/airflow_etl.py', '--cfg-path', '/tmp/tmpo7x3d5oj']
[2025-05-12T09:21:24.828+0000] {standard_task_runner.py:85} INFO - Job 2: Subtask insert_locations
[2025-05-12T09:21:24.882+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations permission to 509
[2025-05-12T09:21:24.883+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations'
[2025-05-12T09:21:24.885+0000] {task_command.py:416} INFO - Running <TaskInstance: Airflow_ETL_DAG.insert_locations scheduled__2025-03-10T00:00:00+00:00 [running]> on host 16fa90749134
[2025-05-12T09:21:24.968+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Airflow_ETL_DAG' AIRFLOW_CTX_TASK_ID='insert_locations' AIRFLOW_CTX_EXECUTION_DATE='2025-03-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-10T00:00:00+00:00'
[2025-05-12T09:21:25.561+0000] {logging_mixin.py:151} INFO - Insertion des locations terminée.
[2025-05-12T09:21:25.564+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-05-12T09:21:25.576+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=Airflow_ETL_DAG, task_id=insert_locations, execution_date=20250310T000000, start_date=20250512T092124, end_date=20250512T092125
[2025-05-12T09:21:25.641+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-05-12T09:21:25.670+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-13T12:50:03.581+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations permission to 509
[2025-05-13T12:50:03.582+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations'
[2025-05-13T12:50:03.635+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations permission to 509
[2025-05-13T12:50:03.635+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations'
[2025-05-13T12:50:03.750+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Airflow_ETL_DAG.insert_locations scheduled__2025-03-10T00:00:00+00:00 [queued]>
[2025-05-13T12:50:03.770+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Airflow_ETL_DAG.insert_locations scheduled__2025-03-10T00:00:00+00:00 [queued]>
[2025-05-13T12:50:03.771+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-05-13T12:50:03.788+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): insert_locations> on 2025-03-10 00:00:00+00:00
[2025-05-13T12:50:03.814+0000] {standard_task_runner.py:57} INFO - Started process 649 to run task
[2025-05-13T12:50:03.827+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'Airflow_ETL_DAG', 'insert_locations', 'scheduled__2025-03-10T00:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/airflow_etl.py', '--cfg-path', '/tmp/tmppkoq90ws']
[2025-05-13T12:50:03.839+0000] {standard_task_runner.py:85} INFO - Job 2: Subtask insert_locations
[2025-05-13T12:50:04.052+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations permission to 509
[2025-05-13T12:50:04.055+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations'
[2025-05-13T12:50:04.059+0000] {task_command.py:416} INFO - Running <TaskInstance: Airflow_ETL_DAG.insert_locations scheduled__2025-03-10T00:00:00+00:00 [running]> on host 1d46261ea2e6
[2025-05-13T12:50:04.267+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Airflow_ETL_DAG' AIRFLOW_CTX_TASK_ID='insert_locations' AIRFLOW_CTX_EXECUTION_DATE='2025-03-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-10T00:00:00+00:00'
[2025-05-13T12:50:05.325+0000] {logging_mixin.py:151} INFO - Insertion des locations terminée.
[2025-05-13T12:50:05.328+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-05-13T12:50:05.337+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=Airflow_ETL_DAG, task_id=insert_locations, execution_date=20250310T000000, start_date=20250513T125003, end_date=20250513T125005
[2025-05-13T12:50:05.371+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-05-13T12:50:05.395+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-06-06T13:39:08.116+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations permission to 509
[2025-06-06T13:39:08.117+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations'
[2025-06-06T13:39:08.177+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations permission to 509
[2025-06-06T13:39:08.178+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations'
[2025-06-06T13:39:08.255+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Airflow_ETL_DAG.insert_locations scheduled__2025-03-10T00:00:00+00:00 [queued]>
[2025-06-06T13:39:08.279+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Airflow_ETL_DAG.insert_locations scheduled__2025-03-10T00:00:00+00:00 [queued]>
[2025-06-06T13:39:08.280+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-06-06T13:39:08.313+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): insert_locations> on 2025-03-10 00:00:00+00:00
[2025-06-06T13:39:08.323+0000] {standard_task_runner.py:57} INFO - Started process 217 to run task
[2025-06-06T13:39:08.329+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'Airflow_ETL_DAG', 'insert_locations', 'scheduled__2025-03-10T00:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/airflow_etl.py', '--cfg-path', '/tmp/tmp66_hzvy8']
[2025-06-06T13:39:08.336+0000] {standard_task_runner.py:85} INFO - Job 2: Subtask insert_locations
[2025-06-06T13:39:08.405+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations permission to 509
[2025-06-06T13:39:08.406+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations'
[2025-06-06T13:39:08.407+0000] {task_command.py:416} INFO - Running <TaskInstance: Airflow_ETL_DAG.insert_locations scheduled__2025-03-10T00:00:00+00:00 [running]> on host 6ddf3bd32fe2
[2025-06-06T13:39:08.514+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Airflow_ETL_DAG' AIRFLOW_CTX_TASK_ID='insert_locations' AIRFLOW_CTX_EXECUTION_DATE='2025-03-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-10T00:00:00+00:00'
[2025-06-06T13:39:08.693+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/airflow_etl.py", line 40, in task_insert_locations
    metadata.reflect(bind=engine)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 4901, in reflect
    Table(name, self, **reflect_opts)
  File "<string>", line 2, in __new__
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/deprecations.py", line 375, in warned
    return fn(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 619, in __new__
    metadata._remove_table(name, schema)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 614, in __new__
    table._init(name, metadata, *args, **kw)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 689, in _init
    self._autoload(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 724, in _autoload
    conn_insp.reflect_table(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/reflection.py", line 795, in reflect_table
    self._reflect_fk(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/reflection.py", line 978, in _reflect_fk
    sa_schema.Table(
  File "<string>", line 2, in __new__
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/deprecations.py", line 375, in warned
    return fn(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 619, in __new__
    metadata._remove_table(name, schema)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 614, in __new__
    table._init(name, metadata, *args, **kw)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 689, in _init
    self._autoload(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 724, in _autoload
    conn_insp.reflect_table(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/reflection.py", line 774, in reflect_table
    for col_d in self.get_columns(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/reflection.py", line 497, in get_columns
    col_defs = self.dialect.get_columns(
  File "<string>", line 2, in get_columns
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/reflection.py", line 55, in cache
    ret = fn(self, con, *args, **kw)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/base.py", line 3856, in get_columns
    table_oid = self.get_table_oid(
  File "<string>", line 2, in get_table_oid
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/reflection.py", line 55, in cache
    ret = fn(self, con, *args, **kw)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/base.py", line 3736, in get_table_oid
    raise exc.NoSuchTableError(table_name)
sqlalchemy.exc.NoSuchTableError: location"
[2025-06-06T13:39:08.715+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=Airflow_ETL_DAG, task_id=insert_locations, execution_date=20250310T000000, start_date=20250606T133908, end_date=20250606T133908
[2025-06-06T13:39:08.728+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 2 for task insert_locations (location"; 217)
[2025-06-06T13:39:08.782+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-06-06T13:39:08.807+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-07T13:35:18.825+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations permission to 509
[2025-06-07T13:35:18.866+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations'
[2025-06-07T13:35:18.935+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations permission to 509
[2025-06-07T13:35:18.936+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations'
[2025-06-07T13:35:19.019+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Airflow_ETL_DAG.insert_locations scheduled__2025-03-10T00:00:00+00:00 [queued]>
[2025-06-07T13:35:19.038+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Airflow_ETL_DAG.insert_locations scheduled__2025-03-10T00:00:00+00:00 [queued]>
[2025-06-07T13:35:19.039+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-06-07T13:35:19.079+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): insert_locations> on 2025-03-10 00:00:00+00:00
[2025-06-07T13:35:19.092+0000] {standard_task_runner.py:57} INFO - Started process 217 to run task
[2025-06-07T13:35:19.102+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'Airflow_ETL_DAG', 'insert_locations', 'scheduled__2025-03-10T00:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/airflow_etl.py', '--cfg-path', '/tmp/tmp99mh226w']
[2025-06-07T13:35:19.108+0000] {standard_task_runner.py:85} INFO - Job 2: Subtask insert_locations
[2025-06-07T13:35:19.359+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations permission to 509
[2025-06-07T13:35:19.360+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations'
[2025-06-07T13:35:19.368+0000] {task_command.py:416} INFO - Running <TaskInstance: Airflow_ETL_DAG.insert_locations scheduled__2025-03-10T00:00:00+00:00 [running]> on host 4cec46ae5e0e
[2025-06-07T13:35:19.580+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Airflow_ETL_DAG' AIRFLOW_CTX_TASK_ID='insert_locations' AIRFLOW_CTX_EXECUTION_DATE='2025-03-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-10T00:00:00+00:00'
[2025-06-07T13:35:19.978+0000] {logging_mixin.py:151} INFO - Erreur dans task_insert_locations: location"
[2025-06-07T13:35:20.248+0000] {logging_mixin.py:151} INFO - Erreur avec approche explicite aussi: location"
[2025-06-07T13:35:20.249+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/airflow_etl.py", line 47, in task_insert_locations
    metadata.reflect(bind=engine)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 4901, in reflect
    Table(name, self, **reflect_opts)
  File "<string>", line 2, in __new__
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/deprecations.py", line 375, in warned
    return fn(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 619, in __new__
    metadata._remove_table(name, schema)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 614, in __new__
    table._init(name, metadata, *args, **kw)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 689, in _init
    self._autoload(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 724, in _autoload
    conn_insp.reflect_table(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/reflection.py", line 795, in reflect_table
    self._reflect_fk(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/reflection.py", line 978, in _reflect_fk
    sa_schema.Table(
  File "<string>", line 2, in __new__
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/deprecations.py", line 375, in warned
    return fn(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 619, in __new__
    metadata._remove_table(name, schema)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 614, in __new__
    table._init(name, metadata, *args, **kw)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 689, in _init
    self._autoload(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 724, in _autoload
    conn_insp.reflect_table(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/reflection.py", line 774, in reflect_table
    for col_d in self.get_columns(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/reflection.py", line 497, in get_columns
    col_defs = self.dialect.get_columns(
  File "<string>", line 2, in get_columns
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/reflection.py", line 55, in cache
    ret = fn(self, con, *args, **kw)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/base.py", line 3856, in get_columns
    table_oid = self.get_table_oid(
  File "<string>", line 2, in get_table_oid
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/reflection.py", line 55, in cache
    ret = fn(self, con, *args, **kw)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/base.py", line 3736, in get_table_oid
    raise exc.NoSuchTableError(table_name)
sqlalchemy.exc.NoSuchTableError: location"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/airflow_etl.py", line 80, in task_insert_locations
    metadata.reflect(bind=engine, schema='pandemics')
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 4901, in reflect
    Table(name, self, **reflect_opts)
  File "<string>", line 2, in __new__
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/deprecations.py", line 375, in warned
    return fn(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 619, in __new__
    metadata._remove_table(name, schema)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 614, in __new__
    table._init(name, metadata, *args, **kw)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 689, in _init
    self._autoload(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 724, in _autoload
    conn_insp.reflect_table(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/reflection.py", line 795, in reflect_table
    self._reflect_fk(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/reflection.py", line 978, in _reflect_fk
    sa_schema.Table(
  File "<string>", line 2, in __new__
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/deprecations.py", line 375, in warned
    return fn(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 619, in __new__
    metadata._remove_table(name, schema)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 614, in __new__
    table._init(name, metadata, *args, **kw)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 689, in _init
    self._autoload(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 724, in _autoload
    conn_insp.reflect_table(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/reflection.py", line 774, in reflect_table
    for col_d in self.get_columns(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/reflection.py", line 497, in get_columns
    col_defs = self.dialect.get_columns(
  File "<string>", line 2, in get_columns
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/reflection.py", line 55, in cache
    ret = fn(self, con, *args, **kw)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/base.py", line 3856, in get_columns
    table_oid = self.get_table_oid(
  File "<string>", line 2, in get_table_oid
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/reflection.py", line 55, in cache
    ret = fn(self, con, *args, **kw)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/base.py", line 3736, in get_table_oid
    raise exc.NoSuchTableError(table_name)
sqlalchemy.exc.NoSuchTableError: location"
[2025-06-07T13:35:20.279+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=Airflow_ETL_DAG, task_id=insert_locations, execution_date=20250310T000000, start_date=20250607T133519, end_date=20250607T133520
[2025-06-07T13:35:20.346+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 2 for task insert_locations (location"; 217)
[2025-06-07T13:35:20.372+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-06-07T13:35:20.422+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-07T14:27:15.173+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations permission to 509
[2025-06-07T14:27:15.225+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations'
[2025-06-07T14:27:15.313+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations permission to 509
[2025-06-07T14:27:15.314+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations'
[2025-06-07T14:27:15.410+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Airflow_ETL_DAG.insert_locations scheduled__2025-03-10T00:00:00+00:00 [queued]>
[2025-06-07T14:27:15.435+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Airflow_ETL_DAG.insert_locations scheduled__2025-03-10T00:00:00+00:00 [queued]>
[2025-06-07T14:27:15.436+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-06-07T14:27:15.504+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): insert_locations> on 2025-03-10 00:00:00+00:00
[2025-06-07T14:27:15.535+0000] {standard_task_runner.py:57} INFO - Started process 228 to run task
[2025-06-07T14:27:15.541+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'Airflow_ETL_DAG', 'insert_locations', 'scheduled__2025-03-10T00:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/airflow_etl.py', '--cfg-path', '/tmp/tmpvzjyxy1a']
[2025-06-07T14:27:15.549+0000] {standard_task_runner.py:85} INFO - Job 2: Subtask insert_locations
[2025-06-07T14:27:15.664+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations permission to 509
[2025-06-07T14:27:15.665+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations'
[2025-06-07T14:27:15.668+0000] {task_command.py:416} INFO - Running <TaskInstance: Airflow_ETL_DAG.insert_locations scheduled__2025-03-10T00:00:00+00:00 [running]> on host fad517f3b141
[2025-06-07T14:27:15.847+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Airflow_ETL_DAG' AIRFLOW_CTX_TASK_ID='insert_locations' AIRFLOW_CTX_EXECUTION_DATE='2025-03-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-10T00:00:00+00:00'
[2025-06-07T14:27:16.281+0000] {logging_mixin.py:151} INFO - Table utilisée: pandemics.location
[2025-06-07T14:27:17.719+0000] {logging_mixin.py:151} INFO - Insertion des locations terminée.
[2025-06-07T14:27:17.726+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-06-07T14:27:17.744+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=Airflow_ETL_DAG, task_id=insert_locations, execution_date=20250310T000000, start_date=20250607T142715, end_date=20250607T142717
[2025-06-07T14:27:17.810+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-06-07T14:27:17.864+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-06-23T07:34:46.943+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations permission to 509
[2025-06-23T07:34:46.944+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations'
[2025-06-23T07:34:46.977+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations permission to 509
[2025-06-23T07:34:46.978+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations'
[2025-06-23T07:34:47.016+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Airflow_ETL_DAG.insert_locations scheduled__2025-03-10T00:00:00+00:00 [queued]>
[2025-06-23T07:34:47.026+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Airflow_ETL_DAG.insert_locations scheduled__2025-03-10T00:00:00+00:00 [queued]>
[2025-06-23T07:34:47.027+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-06-23T07:34:47.043+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): insert_locations> on 2025-03-10 00:00:00+00:00
[2025-06-23T07:34:47.051+0000] {standard_task_runner.py:57} INFO - Started process 266 to run task
[2025-06-23T07:34:47.055+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'Airflow_ETL_DAG', 'insert_locations', 'scheduled__2025-03-10T00:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/airflow_etl.py', '--cfg-path', '/tmp/tmpriby2ava']
[2025-06-23T07:34:47.058+0000] {standard_task_runner.py:85} INFO - Job 2: Subtask insert_locations
[2025-06-23T07:34:47.118+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations permission to 509
[2025-06-23T07:34:47.119+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=Airflow_ETL_DAG/run_id=scheduled__2025-03-10T00:00:00+00:00/task_id=insert_locations'
[2025-06-23T07:34:47.121+0000] {task_command.py:416} INFO - Running <TaskInstance: Airflow_ETL_DAG.insert_locations scheduled__2025-03-10T00:00:00+00:00 [running]> on host ac5b3d82d6a8
[2025-06-23T07:34:47.207+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Airflow_ETL_DAG' AIRFLOW_CTX_TASK_ID='insert_locations' AIRFLOW_CTX_EXECUTION_DATE='2025-03-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-10T00:00:00+00:00'
[2025-06-23T07:34:47.449+0000] {logging_mixin.py:151} INFO - Table utilisée: pandemics.location
[2025-06-23T07:34:48.066+0000] {logging_mixin.py:151} INFO - Insertion des locations terminée.
[2025-06-23T07:34:48.069+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-06-23T07:34:48.080+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=Airflow_ETL_DAG, task_id=insert_locations, execution_date=20250310T000000, start_date=20250623T073447, end_date=20250623T073448
[2025-06-23T07:34:48.111+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-06-23T07:34:48.137+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
